### ISSUE TITLE
Remove the word `Data` from Adonis sidebar options

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/amp-compatibility#111]
Remove the word `data` from the Queue names

<img width="232" alt="Screenshot 2021-03-22 at 7 49 21 PM" src="https://user-images.githubusercontent.com/20221326/112004385-c476f000-8b47-11eb-973b-ed14c0a84d34.png">

**Comment by dhaval-parekh** [comment]
This is completed in #114
