### ISSUE TITLE
rt.gw site for client demo

### ISSUE THREAD

**Issue by rahul286** [rtCamp/amp-compatibility#119]
- [x] Please create a new demo site amp.rt.gw
- [x] Using code at https://github.com/rtCamp/amp-wp/tree/feature/send-button 
- [x] Add GH Action cron or something to keep develop branch at https://github.com/rtCamp/amp-wp/ updated with upstream https://github.com/ampproject/amp-wp/

**Comment by dhsathiya** [comment]
@rahul286 the tasks have been completed.
