### ISSUE TITLE
Configure insights.amp-wp.org

### ISSUE THREAD

**Issue by rahul286** [rtCamp/amp-compatibility#142]
- [x] @gagan0123 @dhsathiya please check what is needed from App Engine side first. Likely it will be a CNAME record mapping. Please provide required value to @westonruter 
- [x] @dhaval-parekh once insights.amp-wp.org starts resolving, check if Adnonis app works nicely. 
- [x] @dhaval-parekh verify google login as return URL would change likely requiring a change in Google Dev Console
- [x] @pdclark please make sure amp-wp plugin code sends data to insights.amp-wp.org

**Comment by gagan0123** [comment]
The person having access to the domain will be able to map that, since it requires verifying the domain that we add.

https://user-images.githubusercontent.com/1535505/115407556-c054f580-a20d-11eb-8a3f-a452b1ed6774.mp4

**Comment by gagan0123** [comment]
The new subdomain mapping is done but Adonis is redirecting to old domain, we will need to change the redirect URL once the user logs in.

**Comment by dhaval-parekh** [comment]
Updates:
- Redirection URL is updated to a new Domain after login from Google.
- Adonis dashboard is working on a new URL.
- Change in WordPress plugin is completed to send data to new URL.
