### ISSUE TITLE
Minor Updates for Data Readability - Adonis Dashboard

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/amp-compatibility#146]
- [ ] Replace `latest version` by ≤  under
- [ ] Remove `from` for Supressed plugin data 
- [ ] Reduce number information. (e.g replace 5000000 by 5M)
- [ ] Add a Partner Flag checkbox

**Comment by dhaval-parekh** [comment]
Implementation of the above change is completed.
