### ISSUE TITLE
support_threads and support_threads_resolved fields have no data

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/amp-compatibility#172]
support_threads and support_threads_resolved fields have no data always shows '0' for themes section in Data Studio Report.

![image](https://user-images.githubusercontent.com/1132541/120685574-9c97f700-c4bd-11eb-9737-4b0f30112b30.png)

**Comment by dhaval-parekh** [comment]
Hey @milindmore22 

We don't have data of "Supported Threads" and "Supported Thread Resolve" for themes. (Something that we don't get from wp.org APIs)

For now, I will remove those column from report.

**Comment by milindmore22** [comment]
Removed LGTM 👍
