### ISSUE TITLE
Not using Latest AMP plugin version be default

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/amp-compatibility#175]
The Adhoc request is not using the latest AMP version, 
Every Adhoc request has coblocks and blocks unit testing plugin in every request do we need it?

example : https://insights.amp-wp.org/admin/report/site/test-adhoc-synthetic-data-2021-06-03-17-47-28.local

![image](https://user-images.githubusercontent.com/1132541/120690290-a53efc00-c4c2-11eb-841f-2bb5fcbd4746.png)

**Comment by dhaval-parekh** [comment]
Hey @milindmore22 

I have updated the script. It will use the latest version of the WordPress plugin. Please verify that at your end.

**Comment by milindmore22** [comment]
Hello @dhaval-parekh 

The AMP plugin is updated, if we are keeping coblock plugin can we please keep it to the latest version too.

**Comment by milindmore22** [comment]
LGTM 👍
