### ISSUE TITLE
URL Count is 2? even for hello dolly plugin

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/amp-compatibility#177]
![image](https://user-images.githubusercontent.com/1132541/120692427-5fcffe00-c4c5-11eb-9ae6-3a2cc292e7c6.png)

**Comment by dhaval-parekh** [comment]
Hey @milindmore22 

I have updated the logic to prevent sending URL data that has no error.

**Comment by milindmore22** [comment]
LGTM 👍
