### ISSUE TITLE
Test with WooCommerce and Storefront Theme fails 

### ISSUE THREAD

**Issue by milindmore22** [rtCamp/amp-compatibility#180]
I did two Adhoc tests WooCommerce and Storefront both failed

https://insights.amp-wp.org/admin/adhoc-synthetic-queue/failed

the error `Fail to send AMP data`

**Comment by dhaval-parekh** [comment]
Hey @milindmore22 

I have addressed that issue.
I retried "WC-test-adhoc-synthetic-data-2021-06-07-13-35-15.local" job. and it's successfully completed. Could you please confirm this at your end?

**Comment by milindmore22** [comment]
LGTM 👍
