### ISSUE TITLE
Review: AMP Dummy Generator Plugin

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/amp-compatibility#73]
Hi Team,

Please could we have your review for the AMP Dummy Generator Plugin as it is an important component. 

It is a plugin to generate dummy data for the sites that will be used in the process of synthetic data generation. It is based on Weston’s approach of automated importing + testing workflow and Felix’s approach of AMP compatibility suite plugin.

While the development of this plugin is still underway, it would be great to have an initial review that will help cover all edge cases and work on any areas of improvement recommended.

**Direct Link** - https://github.com/rtCamp/amp-compatibility/tree/main/amp-wp-dummy-data-generator

**Comment by felixarntz** [comment]
I've left my code review feedback on #75 as well.
