### ISSUE TITLE
'Retry' Option - Adonis Dashboard

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/amp-compatibility#94]
**Request** - When clicking on “Retry” for a job it’s greyed out but not entirely clear it’s no longer clickable. 

Lighten colour even further. 

**Slack Thread** - https://rtcamp.slack.com/archives/G01E8C3JT45/p1614794760004300

**Comment by dhaval-parekh** [comment]
I have addressed this in PR #100. Now job's row will be removed from the table when action is completed
