### ISSUE TITLE
Debug : Issue with node ace migration:run

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/amp-compatibility#96]
**Problem** - getting a connection refused error when I try to run `node ace migration:run` – here’s my (Bethany's) [`.env` file ](https://drive.google.com/file/d/1CVlM3dtmDgx4ygaX1MhKbi-IofIaD9ij/view?usp=sharing)if someone wants to take a look

_Request access to the file_

**Slack Thread** - https://rtcamp.slack.com/archives/G01E8C3JT45/p1614794760004300

**Comment by dhaval-parekh** [comment]
I have checked the .env file and the "GOOGLE_APPLICATION_CREDENTIALS" variable is empty. Which is a path of service account JSON file to access GCP services.
Since it's missing, the application is not able to create/destroy the BigQuery dataset and its tables.
