### ISSUE TITLE
Adonis Dashboard - Feature Suggestions

### ISSUE THREAD

**Issue by maitreyie-chavan** [rtCamp/amp-compatibility#97]
- [x] Possibility to add a link to a zip file for AMP plugin source
- [x] Alberto proposed one should be able to go to a specific Adhoc report and get all data related to it
Possible solution: Click on a particular report URL in Adonis, and then land up in Data Studio report for that particular Adhoc request.

**Slack Threads**

https://rtcamp.slack.com/archives/C01E68NLNRG/p1614806881011100

**Comment by dhaval-parekh** [comment]
> Possibility to add a link to a zip file for AMP plugin source.
Implementation is completed in this PR  #99 

About the list of reports in the adonis dashboard, This can be achieved when we have the site report ready in the Data studio.

**Comment by maitreyie-chavan** [comment]
Both the suggestions have been implemented.
